spring.application.name=rentflow

# ===================================================================
# Database Configuration (for Neon)
# ===================================================================
spring.datasource.url=jdbc:postgresql://ep-fancy-lab-at3b1tw7.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_4rheyQj6cOGi
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===================================================================
# JWT Configuration
# ===================================================================
jwt.secret=N8qA/K8bTv6d2V2Y9v1zZg4hJ0l3s6w9y$B&E)H@McQfTjWnZr4u7x!
jwt.expiration=86400000

# ===================================================================
# Third-Party Service Keys
# ===================================================================
paystack.secret.key=sk_test_14ccae9b82b6789c33bdeee33a7ac712227738b9

server.address=0.0.0.0
server.port=8080