spring.application.name=rentflow

# ===================================================================
# Database Configuration (for Neon)
# ===================================================================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# ===================================================================
# JWT Configuration
# ===================================================================
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# ===================================================================
# Third-Party Service Keys
# ===================================================================
paystack.secret.key=${PAYSTACK_SECRET_KEY}

server.address=0.0.0.0
server.port=8080